#!/usr/bin/env python3
"""Build a GitHub Pages site by converting PDFs in ./pdfs into a static site.

Updated goal (interactive-PDF friendly):
- Preserve PDF interactivity better (links + selectable text) by using PDF.js.
- Publish a single entry point: `/index.html`.
- Display one page at a time, fit-to-screen and centered.
- Navigate pages with left/right arrows.

Implementation:
- Copy the first PDF from ./pdfs into dist/document.pdf.
- Generate dist/index.html that loads PDF.js from a CDN and renders the page
  to a canvas with a text layer + annotation layer.

Notes:
- This preserves links and selectable text for most PDFs.
- You must open the site via a web server (GitHub Pages / localhost). Some
  browsers block PDF loading from file:// for security reasons.
"""

from __future__ import annotations

import html
import shutil
from pathlib import Path

from pypdf import PdfReader

ROOT = Path(__file__).resolve().parents[1]
PDF_DIR = ROOT / "pdfs"
DIST_DIR = ROOT / "dist"


def ensure_empty_dir(p: Path) -> None:
    if p.exists():
        shutil.rmtree(p)
    p.mkdir(parents=True, exist_ok=True)


def site_html(pdf_rel_path: str, title: str, total_pages: int) -> str:
    safe_title = html.escape(title)

    # PDF.js from CDN.
    # We load both the core library and viewer helpers (text + annotation layers).
    pdfjs_ver = "4.10.38"
    pdfjs_build = f"https://cdn.jsdelivr.net/npm/pdfjs-dist@{pdfjs_ver}/build"
    pdfjs_web = f"https://cdn.jsdelivr.net/npm/pdfjs-dist@{pdfjs_ver}/web"

    return (
        "<!doctype html>\n"
        "<html lang=\"en\">\n"
        "  <head>\n"
        "    <meta charset=\"utf-8\" />\n"
        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, viewport-fit=cover, user-scalable=yes\" />\n"
        f"    <title>{safe_title}</title>\n"
        f"    <link rel=\"stylesheet\" href=\"{pdfjs_web}/pdf_viewer.css\" />\n"
        "    <style>\n"
        "      :root {\n"
        "        color-scheme: light;\n"
        "        --pad-top: env(safe-area-inset-top, 0px);\n"
        "        --pad-right: env(safe-area-inset-right, 0px);\n"
        "        --pad-bottom: env(safe-area-inset-bottom, 0px);\n"
        "        --pad-left: env(safe-area-inset-left, 0px);\n"
        "        --fit-scale: 0.95;\n"
        "        --gutter: 72px;\n"
        "      }\n"
        "      html, body { height: 100%; width: 100%; }\n"
        "      body { margin: 0; overflow: hidden; background: #fff; -webkit-text-size-adjust: 100%; }\n"
        "\n"
        "      .viewer {\n"
        "        height: 100vh;\n"
        "        width: 100vw;\n"
        "        display: grid;\n"
        "        grid-template-columns: var(--gutter) 1fr var(--gutter);\n"
        "        align-items: center;\n"
        "        position: relative;\n"
        "        background: #fff;\n"
        "        padding: var(--pad-top) var(--pad-right) var(--pad-bottom) var(--pad-left);\n"
        "        box-sizing: border-box;\n"
        "      }\n"
        "\n"
        "      .content {\n"
        "        grid-column: 2;\n"
        "        height: 100%;\n"
        "        width: 100%;\n"
        "        display: grid;\n"
        "        place-items: center;\n"
        "        overflow: hidden;\n"
        "      }\n"
        "\n"
        "      .pan {\n"
        "        height: 100%;\n"
        "        width: 100%;\n"
        "        overflow: hidden;\n"
        "        display: grid;\n"
        "        align-items: center;\n"
        "        justify-items: center;\n"
        "        -webkit-overflow-scrolling: touch;\n"
        "        touch-action: pan-x pan-y;\n"
        "      }\n"
        "      .pan.is-zoomed { overflow: auto; }\n"
        "\n"
        "      .page-stage {\n"
        "        position: relative;\n"
        "        display: inline-block;\n"
        "      }\n"
        "\n"
        "      #pdfCanvas {\n"
        "        display: block;\n"
        "        transform-origin: center center;\n"
        "        user-select: none;\n"
        "        -webkit-user-drag: none;\n"
        "      }\n"
        "\n"
        "      /* The PDF viewer CSS expects these classes in some cases; keep them absolute */\n"
        "      .textLayer { position: absolute; inset: 0; transform-origin: 0 0; overflow: hidden; }\n"
        "      .annotationLayer { position: absolute; inset: 0; transform-origin: 0 0; }\n"
        "\n"
        "      .nav {\n"
        "        height: 100%;\n"
        "        display: grid;\n"
        "        place-items: center;\n"
        "        cursor: pointer;\n"
        "        user-select: none;\n"
        "        -webkit-tap-highlight-color: transparent;\n"
        "        color: rgba(0,0,0,0.65);\n"
        "        font: 700 40px/1 system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif;\n"
        "      }\n"
        "      .nav:hover { color: rgba(0,0,0,0.9); }\n"
        "      .nav[aria-disabled=\"true\"] { opacity: 0; pointer-events: none; }\n"
        "      .nav-left { grid-column: 1; background: linear-gradient(to right, rgba(255,255,255,0.80), rgba(255,255,255,0)); }\n"
        "      .nav-right { grid-column: 3; background: linear-gradient(to left, rgba(255,255,255,0.80), rgba(255,255,255,0)); }\n"
        "\n"
        "      .counter {\n"
        "        position: absolute;\n"
        "        bottom: calc(10px + var(--pad-bottom));\n"
        "        left: 50%;\n"
        "        transform: translateX(-50%);\n"
        "        padding: 6px 10px;\n"
        "        border-radius: 999px;\n"
        "        background: rgba(255,255,255,0.75);\n"
        "        color: rgba(0,0,0,0.75);\n"
        "        font: 600 12px/1.2 system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif;\n"
        "        pointer-events: none;\n"
        "      }\n"
        "\n"
        "      .status {\n"
        "        position: absolute;\n"
        "        top: calc(10px + var(--pad-top));\n"
        "        left: 50%;\n"
        "        transform: translateX(-50%);\n"
        "        padding: 6px 10px;\n"
        "        border-radius: 999px;\n"
        "        background: rgba(0,0,0,0.06);\n"
        "        color: rgba(0,0,0,0.75);\n"
        "        font: 600 12px/1.2 system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif;\n"
        "      }\n"
        "\n"
        "      @media (max-width: 720px) {\n"
        "        :root { --gutter: 64px; }\n"
        "        .nav { font-size: 34px; }\n"
        "      }\n"
        "\n"
        "      * { box-sizing: border-box; }\n"
        "    </style>\n"
        "  </head>\n"
        "  <body>\n"
        "    <div class=\"viewer\" id=\"viewer\">\n"
        "      <div class=\"nav nav-left\" id=\"prevBtn\" aria-label=\"Previous page\" role=\"button\" tabindex=\"0\">&#10094;</div>\n"
        "      <div class=\"content\">\n"
        "        <div class=\"pan\" id=\"pan\">\n"
        "          <div class=\"page-stage\" id=\"stage\">\n"
        "            <canvas id=\"pdfCanvas\"></canvas>\n"
        "            <div class=\"textLayer\" id=\"textLayer\"></div>\n"
        "            <div class=\"annotationLayer\" id=\"annotationLayer\"></div>\n"
        "          </div>\n"
        "        </div>\n"
        "      </div>\n"
        "      <div class=\"nav nav-right\" id=\"nextBtn\" aria-label=\"Next page\" role=\"button\" tabindex=\"0\">&#10095;</div>\n"
        "      <div class=\"counter\" id=\"counter\"></div>\n"
        "      <div class=\"status\" id=\"status\">Loading…</div>\n"
        "    </div>\n"
        "\n"
        "    <script type=\"module\">\n"
        f"      import * as pdfjsLib from '{pdfjs_build}/pdf.min.mjs';\n"
        f"      import * as pdfjsViewer from '{pdfjs_web}/pdf_viewer.mjs';\n"
        "\n"
        "      const PDF_URL = "
        + repr(pdf_rel_path)
        + ";\n"
        f"      const PDF_PAGES = {int(total_pages) if total_pages else 0};\n"
        "\n"
        "      const pan = document.getElementById('pan');\n"
        "      const stage = document.getElementById('stage');\n"
        "      const canvas = document.getElementById('pdfCanvas');\n"
        "      const textLayerDiv = document.getElementById('textLayer');\n"
        "      const annotationLayerDiv = document.getElementById('annotationLayer');\n"
        "      const prevBtn = document.getElementById('prevBtn');\n"
        "      const nextBtn = document.getElementById('nextBtn');\n"
        "      const counter = document.getElementById('counter');\n"
        "      const status = document.getElementById('status');\n"
        "\n"
        "      let pdfDoc = null;\n"
        "      let pageNumber = 1;\n"
        "      let baseScale = 1;\n"
        "      let zoom = 1;\n"
        "\n"
        "      function setStatus(msg) { status.textContent = msg; status.style.display = msg ? 'block' : 'none'; }\n"
        "      function clamp(n, lo, hi) { return Math.max(lo, Math.min(hi, n)); }\n"
        "\n"
        "      function computeBaseScale(viewportW, viewportH) {\n"
        "        const cs = getComputedStyle(document.documentElement);\n"
        "        const padTop = parseFloat(cs.getPropertyValue('--pad-top')) || 0;\n"
        "        const padRight = parseFloat(cs.getPropertyValue('--pad-right')) || 0;\n"
        "        const padBottom = parseFloat(cs.getPropertyValue('--pad-bottom')) || 0;\n"
        "        const padLeft = parseFloat(cs.getPropertyValue('--pad-left')) || 0;\n"
        "        const gutter = parseFloat(cs.getPropertyValue('--gutter')) || 0;\n"
        "        const fitScale = parseFloat(cs.getPropertyValue('--fit-scale')) || 1;\n"
        "        const margin = 4;\n"
        "        const availW = Math.max(1, window.innerWidth - padLeft - padRight - (2 * gutter) - margin);\n"
        "        const availH = Math.max(1, window.innerHeight - padTop - padBottom - margin);\n"
        "        const s = Math.min(availW / viewportW, availH / viewportH) * fitScale;\n"
        "        baseScale = clamp(s, 0.01, 10);\n"
        "      }\n"
        "\n"
        "      function applyScale() {\n"
        "        const s = baseScale * zoom;\n"
        "        stage.style.transform = `scale(${s})`;\n"
        "        stage.style.transformOrigin = 'center center';\n"
        "        pan.classList.toggle('is-zoomed', zoom > 1.01);\n"
        "      }\n"
        "\n"
        "      function recenter() {\n"
        "        const maxX = Math.max(0, pan.scrollWidth - pan.clientWidth);\n"
        "        const maxY = Math.max(0, pan.scrollHeight - pan.clientHeight);\n"
        "        pan.scrollLeft = maxX / 2;\n"
        "        pan.scrollTop = maxY / 2;\n"
        "      }\n"
        "\n"
        "      function setNavState() {\n"
        "        const total = pdfDoc?.numPages || PDF_PAGES || 0;\n"
        "        counter.textContent = total ? `${pageNumber} / ${total}` : '';\n"
        "        prevBtn.setAttribute('aria-disabled', String(pageNumber <= 1));\n"
        "        nextBtn.setAttribute('aria-disabled', String(total && pageNumber >= total));\n"
        "      }\n"
        "\n"
        "      function next() { if (pdfDoc && pageNumber < pdfDoc.numPages) renderPage(pageNumber + 1); }\n"
        "      function prev() { if (pdfDoc && pageNumber > 1) renderPage(pageNumber - 1); }\n"
        "\n"
        "      prevBtn.addEventListener('click', prev);\n"
        "      nextBtn.addEventListener('click', next);\n"
        "\n"
        "      window.addEventListener('keydown', (e) => {\n"
        "        if (e.key === 'ArrowRight') next();\n"
        "        if (e.key === 'ArrowLeft') prev();\n"
        "        if (e.key === '+' || e.key === '=') { zoom = clamp(zoom * 1.1, 1, 8); applyScale(); }\n"
        "        if (e.key === '-') { zoom = clamp(zoom / 1.1, 1, 8); applyScale(); }\n"
        "        if (e.key === '0') { zoom = 1; applyScale(); recenter(); }\n"
        "      });\n"
        "\n"
        "      window.addEventListener('resize', () => { applyScale(); recenter(); });\n"
        "      window.addEventListener('orientationchange', () => { setTimeout(() => { applyScale(); recenter(); }, 150); });\n"
        "\n"
        "      pan.addEventListener('wheel', (e) => {\n"
        "        if (!(e.ctrlKey || e.metaKey)) return;\n"
        "        e.preventDefault();\n"
        "        const delta = e.deltaY;\n"
        "        zoom = clamp(zoom * (delta > 0 ? 0.9 : 1.1), 1, 8);\n"
        "        applyScale();\n"
        "        recenter();\n"
        "      }, { passive: false });\n"
        "\n"
        "      // Pinch-to-zoom\n"
        "      let pinchActive = false;\n"
        "      let pinchStartDist = 0;\n"
        "      let pinchStartZoom = 1;\n"
        "      function touchDist(t1, t2) {\n"
        "        const dx = t1.clientX - t2.clientX;\n"
        "        const dy = t1.clientY - t2.clientY;\n"
        "        return Math.hypot(dx, dy);\n"
        "      }\n"
        "      pan.addEventListener('touchstart', (e) => {\n"
        "        if (!e.touches || e.touches.length !== 2) return;\n"
        "        pinchActive = true;\n"
        "        pinchStartDist = touchDist(e.touches[0], e.touches[1]);\n"
        "        pinchStartZoom = zoom;\n"
        "      }, { passive: true });\n"
        "      pan.addEventListener('touchmove', (e) => {\n"
        "        if (!pinchActive || !e.touches || e.touches.length !== 2) return;\n"
        "        e.preventDefault();\n"
        "        const curDist = touchDist(e.touches[0], e.touches[1]);\n"
        "        if (pinchStartDist <= 0) return;\n"
        "        const ratio = curDist / pinchStartDist;\n"
        "        zoom = clamp(pinchStartZoom * ratio, 1, 8);\n"
        "        applyScale();\n"
        "      }, { passive: false });\n"
        "      pan.addEventListener('touchend', (e) => {\n"
        "        if (!pinchActive) return;\n"
        "        if (!e.touches || e.touches.length < 2) {\n"
        "          pinchActive = false;\n"
        "          recenter();\n"
        "        }\n"
        "      }, { passive: true });\n"
        "      pan.addEventListener('touchcancel', () => { pinchActive = false; }, { passive: true });\n"
        "\n"
        "      async function renderPage(num) {\n"
        "        if (!pdfDoc) return;\n"
        "        pageNumber = clamp(num, 1, pdfDoc.numPages);\n"
        "        setNavState();\n"
        "        setStatus('Rendering…');\n"
        "        zoom = 1;\n"
        "\n"
        "        const page = await pdfDoc.getPage(pageNumber);\n"
        "        const viewport = page.getViewport({ scale: 1 });\n"
        "\n"
        "        const outputScale = window.devicePixelRatio || 1;\n"
        "        canvas.width = Math.floor(viewport.width * outputScale);\n"
        "        canvas.height = Math.floor(viewport.height * outputScale);\n"
        "        canvas.style.width = `${viewport.width}px`;\n"
        "        canvas.style.height = `${viewport.height}px`;\n"
        "\n"
        "        stage.style.width = `${viewport.width}px`;\n"
        "        stage.style.height = `${viewport.height}px`;\n"
        "        textLayerDiv.replaceChildren();\n"
        "        annotationLayerDiv.replaceChildren();\n"
        "\n"
        "        const ctx = canvas.getContext('2d', { alpha: false });\n"
        "        const transform = outputScale !== 1 ? [outputScale, 0, 0, outputScale, 0, 0] : null;\n"
        "\n"
        "        await page.render({ canvasContext: ctx, viewport, transform }).promise;\n"
        "\n"
        "        computeBaseScale(viewport.width, viewport.height);\n"
        "        applyScale();\n"
        "        recenter();\n"
        "\n"
        "        // Text layer (selection/search)\n"
        "        const textContent = await page.getTextContent();\n"
        "        await pdfjsViewer.renderTextLayer({\n"
        "          textContentSource: textContent,\n"
        "          container: textLayerDiv,\n"
        "          viewport,\n"
        "        });\n"
        "\n"
        "        // Annotation layer (links, forms)\n"
        "        const linkService = new pdfjsViewer.PDFLinkService();\n"
        "        linkService.setDocument(pdfDoc);\n"
        "        const annotations = await page.getAnnotations();\n"
        "        pdfjsViewer.AnnotationLayer.render({\n"
        "          viewport,\n"
        "          div: annotationLayerDiv,\n"
        "          annotations,\n"
        "          page,\n"
        "          linkService,\n"
        "          renderForms: true,\n"
        "        });\n"
        "\n"
        "        setStatus('');\n"
        "      }\n"
        "\n"
        "      // Load PDF\n"
        f"      pdfjsLib.GlobalWorkerOptions.workerSrc = '{pdfjs_build}/pdf.worker.min.mjs';\n"
        "\n"
        "      setStatus('Loading PDF…');\n"
        "      const loadingTask = pdfjsLib.getDocument({ url: PDF_URL });\n"
        "      loadingTask.promise.then((doc) => {\n"
        "        pdfDoc = doc;\n"
        "        setNavState();\n"
        "        renderPage(1);\n"
        "      }).catch((err) => {\n"
        "        setStatus('Failed to load PDF.');\n"
        "        console.error(err);\n"
        "      });\n"
        "    </script>\n"
        "  </body>\n"
        "</html>\n"
    )


def main() -> None:
    ensure_empty_dir(DIST_DIR)

    if not PDF_DIR.exists():
        raise RuntimeError("Missing ./pdfs directory")

    pdf_paths = sorted([p for p in PDF_DIR.iterdir() if p.suffix.lower() == ".pdf"])
    if not pdf_paths:
        raise RuntimeError("No PDFs found in ./pdfs")

    # Keep behavior simple and deterministic: publish the first PDF in sorted order.
    pdf_path = pdf_paths[0]

    # Read page count for nav state.
    reader = PdfReader(str(pdf_path))
    total_pages = len(reader.pages)

    # Copy PDF into dist. Use a stable filename for index.html to reference.
    out_pdf = DIST_DIR / "document.pdf"
    shutil.copyfile(pdf_path, out_pdf)

    # Generate index.html as the only entry point.
    (DIST_DIR / "index.html").write_text(
        site_html("./document.pdf", title="Portfolio Architecture", total_pages=total_pages),
        encoding="utf-8",
    )

    print(f"Built interactive-friendly site for: {pdf_path.name}. Output: {DIST_DIR}")


if __name__ == "__main__":
    main()

